apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
        - name: netflix-clone
          image: boluex/netflix_clone:latest
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: netflix-clone
spec:
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

